### ISSUE TITLE
fly control plane

### ISSUE THREAD

**Issue by gedw99** [jtarchie/forum#2]
https://github.com/sosedoff/fly-machines/

**Comment by gedw99** [comment]
like the overmind trick.  Now you got docker compose on fly :)

I am very tempted to build a overmind control plane. Not sure yet..

**Comment by jtarchie** [comment]
It was in their docs. Cannot get link at the moment. Is this an ad issue?

**Comment by gedw99** [comment]
> 



> It was in their docs. Cannot get link at the moment. Is this an ad issue?

add issue ? sorry dont know what you mean ?

**Comment by jtarchie** [comment]
I'm sorry for the confusion.  An ad, as in, you are advertising a repo? 

It needs to be clarified what the issue is about. Can you clarify the intention, please?

**Comment by jtarchie** [comment]
Thanks for the lead. At the moment, I am happy to use the CLI because it does the initial setup and the `Dockerfile` build automagically. I will perhaps automate it in the future, but CLI does it all for now.
